"""minor_change

Revision ID: 004da9b043c2
Revises: 225e979050f1
Create Date: 2026-09-22 21:20:37.243304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '004da9b043c2'
down_revision: Union[str, Sequence[str], None] = '225e979050f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('unique_cik_fiscal_year_period'), 'financial_facts', type_='unique')
    op.create_unique_constraint('unique_cik_fiscal_year_period', 'financial_facts', ['filing_id', 'concept_id', 'human_label'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_cik_fiscal_year_period', 'financial_facts', type_='unique')
    op.create_unique_constraint(op.f('unique_cik_fiscal_year_period'), 'financial_facts', ['cik', 'fiscal_year', 'period', 'concept_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
