"""minor_change

Revision ID: 225e979050f1
Revises: 80556b2a84b0
Create Date: 2026-09-22 21:10:49.490938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '225e979050f1'
down_revision: Union[str, Sequence[str], None] = '80556b2a84b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_cik_fiscal_year_period', 'financial_facts', ['cik', 'fiscal_year', 'period', 'concept_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_cik_fiscal_year_period', 'financial_facts', type_='unique')
    # ### end Alembic commands ###
