"""Initial tables

Revision ID: 2b96ae5cded6
Revises: 
Create Date: 2026-08-20 00:45:03.563271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b96ae5cded6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('cik', sa.String(length=10), nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('exchange', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('cik'),
    sa.UniqueConstraint('ticker')
    )
    op.create_index('idx_companies_ticker', 'companies', ['ticker'], unique=False)
    op.create_table('standard_concepts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('concept_key', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('concept_key')
    )
    op.create_table('filings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cik', sa.String(length=10), nullable=False),
    sa.Column('filing_type', sa.String(length=10), nullable=False),
    sa.Column('filing_url', sa.Text(), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cik'], ['companies.cik'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cik', 'filing_type', 'fiscal_year', 'filing_url', name='uq_filing_entry')
    )
    op.create_index('idx_filings_lookup', 'filings', ['cik', 'fiscal_year', 'filing_type'], unique=False)
    op.create_table('financial_facts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('concept_key', sa.String(length=255), nullable=False),
    sa.Column('cik', sa.String(length=10), nullable=False),
    sa.Column('filing_id', sa.Integer(), nullable=False),
    sa.Column('statement_type', sa.String(length=50), nullable=False),
    sa.Column('period', sa.String(length=10), nullable=False),
    sa.Column('dimension_member', sa.String(length=255), nullable=False),
    sa.Column('value_usd_integer', sa.BigInteger(), nullable=False),
    sa.Column('decimals_exponent', sa.Integer(), nullable=False),
    sa.Column('balance', sa.String(length=10), nullable=False),
    sa.Column('human_label', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cik'], ['companies.cik'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['concept_key'], ['standard_concepts.concept_key'], ),
    sa.ForeignKeyConstraint(['filing_id'], ['filings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cik', 'concept_key', 'period', 'dimension_member', 'filing_id', name='uq_fact_coordinate')
    )
    op.create_index('idx_facts_sandbox_query', 'financial_facts', ['cik', 'concept_key', 'period', 'dimension_member'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_facts_sandbox_query', table_name='financial_facts')
    op.drop_table('financial_facts')
    op.drop_index('idx_filings_lookup', table_name='filings')
    op.drop_table('filings')
    op.drop_table('standard_concepts')
    op.drop_index('idx_companies_ticker', table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
