"""initial_schema

Revision ID: 5111b83eeac6
Revises: 
Create Date: 2026-09-22 10:44:53.039645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5111b83eeac6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('cik', sa.String(length=10), nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('exchange', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('cik'),
    sa.UniqueConstraint('ticker')
    )
    op.create_table('standard_concepts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('concept_key', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('concept_key')
    )
    op.create_table('filings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('accession_number', sa.String(length=25), nullable=False),
    sa.Column('period', sa.String(length=20), nullable=False),
    sa.Column('cik', sa.String(length=10), nullable=False),
    sa.Column('filing_type', sa.String(length=10), nullable=False),
    sa.Column('filing_url', sa.Text(), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cik'], ['companies.cik'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('accession_number')
    )
    op.create_index('idx_filings_lookup', 'filings', ['cik', 'fiscal_year', 'filing_type'], unique=False)
    op.create_table('financial_facts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('concept_key', sa.String(length=255), nullable=False),
    sa.Column('cik', sa.String(length=10), nullable=False),
    sa.Column('filing_id', sa.Integer(), nullable=False),
    sa.Column('statement_type', sa.String(length=50), nullable=False),
    sa.Column('period', sa.String(length=10), nullable=False),
    sa.Column('dimension_member', sa.String(length=255), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('value', sa.Numeric(precision=28, scale=4), nullable=False),
    sa.Column('human_label', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cik'], ['companies.cik'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['concept_key'], ['standard_concepts.concept_key'], ),
    sa.ForeignKeyConstraint(['filing_id'], ['filings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_facts_filing_id', 'financial_facts', ['filing_id', 'concept_key'], unique=False)
    op.create_index('idx_facts_sandbox_query', 'financial_facts', ['cik', 'fiscal_year', 'period', 'concept_key'], unique=False)
    op.create_table('parent_chunks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cik', sa.String(length=10), nullable=False),
    sa.Column('filing_id', sa.Integer(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('section_name', sa.String(length=100), nullable=False),
    sa.Column('text_content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cik'], ['companies.cik'], name='fk_parents_company', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['filing_id'], ['filings.id'], name='fk_parents_filing', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_parent_chunks_cik', 'parent_chunks', ['cik'], unique=False)
    op.create_index('idx_parent_chunks_filing_id', 'parent_chunks', ['filing_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_parent_chunks_filing_id', table_name='parent_chunks')
    op.drop_index('idx_parent_chunks_cik', table_name='parent_chunks')
    op.drop_table('parent_chunks')
    op.drop_index('idx_facts_sandbox_query', table_name='financial_facts')
    op.drop_index('idx_facts_filing_id', table_name='financial_facts')
    op.drop_table('financial_facts')
    op.drop_index('idx_filings_lookup', table_name='filings')
    op.drop_table('filings')
    op.drop_table('standard_concepts')
    op.drop_table('companies')
    # ### end Alembic commands ###
