"""minor_change

Revision ID: 80f44ffcadbd
Revises: b3ace5b07d71
Create Date: 2026-09-23 11:42:04.408037

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80f44ffcadbd'
down_revision: Union[str, Sequence[str], None] = 'b3ace5b07d71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('unique_cik_fiscal_year_period'), 'financial_facts', type_='unique')
    op.create_unique_constraint('unique_cik_fiscal_year_period', 'financial_facts', ['filing_id', 'concept_id', 'human_label', 'dimension_member', 'raw_concept'], postgresql_nulls_not_distinct=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_cik_fiscal_year_period', 'financial_facts', type_='unique')
    op.create_unique_constraint(op.f('unique_cik_fiscal_year_period'), 'financial_facts', ['filing_id', 'concept_id', 'human_label', 'dimension_member'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
