"""minor_change

Revision ID: 89fb7ddda1ef
Revises: 004da9b043c2
Create Date: 2026-09-22 22:24:35.182443

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89fb7ddda1ef'
down_revision: Union[str, Sequence[str], None] = '004da9b043c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('unique_cik_fiscal_year_period'), 'financial_facts', type_='unique')
    op.create_unique_constraint('unique_cik_fiscal_year_period', 'financial_facts', ['filing_id', 'concept_id', 'human_label', 'dimension_member'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_cik_fiscal_year_period', 'financial_facts', type_='unique')
    op.create_unique_constraint(op.f('unique_cik_fiscal_year_period'), 'financial_facts', ['filing_id', 'concept_id', 'human_label'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
