"""minor_change

Revision ID: adc336cf6964
Revises: 5111b83eeac6
Create Date: 2026-09-22 11:51:34.134100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'adc336cf6964'
down_revision: Union[str, Sequence[str], None] = '5111b83eeac6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('financial_facts', sa.Column('concept_id', sa.Integer(), nullable=False))
    op.drop_index(op.f('idx_facts_filing_id'), table_name='financial_facts')
    op.create_index('idx_facts_filing_id', 'financial_facts', ['filing_id', 'concept_id'], unique=False)
    op.drop_index(op.f('idx_facts_sandbox_query'), table_name='financial_facts')
    op.create_index('idx_facts_sandbox_query', 'financial_facts', ['cik', 'fiscal_year', 'period', 'concept_id'], unique=False)
    op.drop_constraint(op.f('financial_facts_concept_key_fkey'), 'financial_facts', type_='foreignkey')
    op.create_foreign_key(None, 'financial_facts', 'standard_concepts', ['concept_id'], ['id'])
    op.drop_column('financial_facts', 'concept_key')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('financial_facts', sa.Column('concept_key', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'financial_facts', type_='foreignkey')
    op.create_foreign_key(op.f('financial_facts_concept_key_fkey'), 'financial_facts', 'standard_concepts', ['concept_key'], ['concept_key'])
    op.drop_index('idx_facts_sandbox_query', table_name='financial_facts')
    op.create_index(op.f('idx_facts_sandbox_query'), 'financial_facts', ['cik', 'fiscal_year', 'period', 'concept_key'], unique=False)
    op.drop_index('idx_facts_filing_id', table_name='financial_facts')
    op.create_index(op.f('idx_facts_filing_id'), 'financial_facts', ['filing_id', 'concept_key'], unique=False)
    op.drop_column('financial_facts', 'concept_id')
    # ### end Alembic commands ###
