"""minor_change

Revision ID: b3ace5b07d71
Revises: 89fb7ddda1ef
Create Date: 2026-09-23 09:47:39.227832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3ace5b07d71'
down_revision: Union[str, Sequence[str], None] = '89fb7ddda1ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('financial_facts', sa.Column('raw_concept', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('financial_facts', 'raw_concept')
    # ### end Alembic commands ###
